# Staticman
staticman:
 allowedFields: ['name', 'title', 'description', 'rating']
 branch: master
 commitMessage: "Hey human, here is a new entry."
 filename: "entry{@timestamp}"
 format: yml
 moderation: true
 path: "_data/comments"
 requiredFields: ['name', 'title', 'description', 'rating']
